<?php

/**
 * Virtual Web Platform Configuration
 *
 * This file is autogenerated
 * DO NOT EDIT!
 *
 * @package VWP
 * @subpackage Base
 * @author Ralph Ritoch <rritoch@gmail.com>
 * @copyright (c) Ralph Ritoch - All Rights Reserved
 * @link http://www.vnetpublishing.com VNetPublishing.Com
 * @license http://www.vnetpublishing.com/Legal/Licenses/2010/10/vnetlpl.txt VNETLPL Limited Public License
 * @access private
 */

/**
 * Virtual Web Platform Configuration
 *
 * This class is autogenerated
 * DO NOT EDIT!
 *
 * @package VWP
 * @subpackage Base
 * @author Ralph Ritoch <rritoch@gmail.com>
 * @copyright (c) Ralph Ritoch - All Rights Reserved
 * @link http://www.vnetpublishing.com VNetPublishing.Com
 * @license http://www.vnetpublishing.com/Legal/Licenses/2010/10/vnetlpl.txt VNETLPL Limited Public License
 * @access private
 */

class VConfig
{

    /**
     * @var string $site_name Site Name
     */

    var $site_name = 'Development Server';

    /**
     * @var string $default_database Default database
     */

    var $default_database = null;

    /**
     * @var string $path_separator Directory separator
     */

    var $path_separator = null;

    /**
     * @var string $default_application Default application
     */

    var $default_application = 'content';

    /**
     * @var string $default_language Default language
     */

    var $default_language = 'en';

    /**
     * @var string $default_document_type Document Type
     */

    var $default_document_type = 'html';

    /**
     * @var string $temp_dir Temporary folder
     */

    var $temp_dir = '/tmp';

    /**
     * @var string $shared_path Shared path
     */

    var $shared_path = null;

    /**
     * @var string $timezone System timezone
     */

    var $timezone = 'Asia/Singapore';

    /**
     * @var string $sef_mode Search engine friendly urls [none/sef/rw_sef]
     */

    var $sef_mode = 'none';

    // end class VConfig
}
