<?php

/**
 * Virtual Web Platform Configuration
 *
 * This file is autogenerated
 * DO NOT EDIT!
 *
 * @package VWP
 * @subpackage Base
 * @author Ralph Ritoch
 * @copyright Ralph Ritoch <rritoch@gmail.com>
 * @link http://www.vnetpublishing.com
 * @access private
 */

/**
 * Virtual Web Platform Configuration
 *
 * This class is autogenerated
 * DO NOT EDIT!
 *
 * @package VWP
 * @subpackage Base
 * @author Ralph Ritoch
 * @copyright Ralph Ritoch <rritoch@gmail.com>
 * @link http://www.vnetpublishing.com
 * @access private
 */

class VConfig {


 /**
  * @var string $default_database Default database
  */

 var $default_database = null;

 /**
  * @var string $path_separator Directory separator
  */

 var $path_separator = null;

 /**
  * @var string $default_application Default application
  */

 var $default_application = null;

 /**
  * @var string $default_language Default language
  */

 var $default_language = null;

 /**
  * @var string $temp_dir Temporary folder
  */

 var $temp_dir = null;

 /**
  * @var string $shared_path Shared path
  */

 var $shared_path = null;

 /**
  * @var string $timezone System timezone
  */

 var $timezone = null;

 /**
  * @var string $sef_mode Search engine friendly urls [none/sef/rw_sef]
  */

 var $sef_mode = null;

} // end class
