 <?php
 
/**
 * VWP Configuration Model 
 *  
 * @package    VWP
 * @subpackage Models
 * @author Ralph Ritoch <rritoch@gmail.com>
 * @link http://www.vnetpublishing.com VNetPublishing.Com 
 * @copyright (c) Ralph Ritoch - All rights reserved
 * @license http://www.vnetpublishing.com/Legal/Licenses/2010/10/vnetlpl.txt VNETLPL Limited Public License
 */

/**
 * Require Model Support
 */
  
VWP::RequireLibrary('vwp.model');

/**
 * Require file support
 */

VWP::RequireLibrary('vwp.filesystem.file');

/**
 * VWP Configuration Model 
 *  
 * @package    VWP
 * @subpackage Models
 * @author Ralph Ritoch <rritoch@gmail.com>
 * @link http://www.vnetpublishing.com VNetPublishing.Com 
 * @copyright (c) Ralph Ritoch - All rights reserved
 * @license http://www.vnetpublishing.com/Legal/Licenses/2010/10/vnetlpl.txt VNETLPL Limited Public License
 */

class VWP_Model_Configure extends VModel 
{

	/**	 
	 * Get available configuration settings
	 * 
	 * @return array Available configuration settings
	 * @access private
	 */
	
    function _configInfo() 
    {
        return array(
         'site_name' => array("type"=>"string","desc"=>"Site Name"),
         'default_database'  => array("type"=>"string","desc"=>"Default database"),
         'path_separator' => array("type"=>"string","desc"=>"Directory separator"),
         'default_application' => array("type"=>"string","desc"=>"Default application"),
         'default_language' => array("type"=>"string","desc"=>"Default language"),
         'default_document_type' => array("type"=>"string","desc"=>"Document Type"),
         'temp_dir' => array("type"=>"string","desc"=>"Temporary folder"),
         'shared_path' => array("type"=>"string","desc"=>"Shared path"),
         'timezone' => array("type"=>"string","desc"=>"System timezone"),
         'sef_mode' => array("type"=>"string","desc"=>"Search engine friendly urls [none/sef/rw_sef]"), 
        );
    }
 
    /**
     * Save Configuration Settings
     * 
     * @param array $settings Configuration settings
     * @return boolean|object True on success, error or warning otherwise
     * @access public
     */
 
    function saveConfig($settings) 
    {
 
        $cfgInfo = $this->_configInfo();
  
        $cfg = & VWP::getConfig();
  
        foreach($cfgInfo as $key=>$v) {   
            if (isset($settings[$key])) {
                if (strlen($settings[$key]) < 1) {
                    $cfg->$key = null;
                } else {
                    $cfg->$key = $settings[$key];
                }
            }
        }
      
        $nl = "\r\n";  
        $filedata = '<' . '?php' . $nl.$nl

         .'/' . '**' . $nl
         .' * Virtual Web Platform Configuration' . $nl
         .' *' . $nl 
         .' * This file is autogenerated' . $nl
         .' * DO NOT EDIT!' . $nl  
         .' *' . $nl 
         .' * @package VWP' . $nl
         .' * @subpackage Base' . $nl  
         .' * @author Ralph Ritoch <rritoch@gmail.com>' . $nl 
         .' * @copyright (c) Ralph Ritoch - All Rights Reserved' . $nl
         .' * @link http://www.vnetpublishing.com VNetPublishing.Com' . $nl
         .' * @license http://www.vnetpublishing.com/Legal/Licenses/2010/10/vnetlpl.txt VNETLPL Limited Public License'. $nl         
         .' * @access private' . $nl     
         .' */' . $nl.$nl
         .'/'.'**' . $nl
         .' * Virtual Web Platform Configuration' . $nl
         .' *' . $nl 
         .' * This class is autogenerated' . $nl
         .' * DO NOT EDIT!' . $nl  
         .' *' . $nl 
         .' * @package VWP' . $nl
         .' * @subpackage Base' . $nl  
         .' * @author Ralph Ritoch <rritoch@gmail.com>' . $nl 
         .' * @copyright (c) Ralph Ritoch - All Rights Reserved' . $nl
         .' * @link http://www.vnetpublishing.com VNetPublishing.Com' . $nl
         .' * @license http://www.vnetpublishing.com/Legal/Licenses/2010/10/vnetlpl.txt VNETLPL Limited Public License'. $nl         
         .' * @access private' . $nl     
         .' */'  
         . $nl
         . $nl
         . 'class VConfig'.$nl
         . '{' . $nl;

        foreach($cfgInfo as $key=>$v) {
            $val = $cfg->$key;
            if ($val === null) {
                $outval = "null";
            } elseif ($val === false) {
                $outval = "false";
            } elseif ($val === true) {
                $outval = "true";
            } else {
                $outval = "'" . addslashes($val) . "'";
            }
    
    
            $filedata .= $nl .'    /**'.$nl
                     .'     * @var '.$v["type"].' $' . $key . ' ' .$v["desc"] . $nl
                     .'     */'.$nl.$nl;
        
            $filedata .= '    var $' . $key . ' = ' . $outval . ';' . $nl;    
        }  
  
        $filedata .= $nl . '    /'.'/ end class VConfig'. $nl . '}'.$nl;
  
        $vfile =& v()->filesystem()->file();
        return $vfile->write(VPATH_BASE.DS.'vwp_config.php',$filedata);     
    }
 
    /**     
     * Get configuration settings
     *
     * @return array Configuration settings
     * @access public
     */
    
    function getConfig() 
    {
        $cfg = VWP::getConfig();
        $vars = get_object_vars($cfg);
        return $vars;
    }
     
    // end class VWP_Model_Config
} 
